
name: Linux builder containers

on:
  workflow_dispatch:

#  schedule:
#  - cron: '30 4 * * 1'

# =========================================================================

jobs:

  # -----------------------------------------------------------------------
  containers:
    runs-on: ubuntu-18.04
    name: Build pak builder containers
    strategy:
      fail-fast: false
      matrix:
        config:
          - { r: '4.3' }
          - { r: '4.2' }
          - { r: '4.1' }
          - { r: '4.0' }
          - { r: '3.6' }
          - { r: '3.5' }
          - { r: '3.4' }

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: tools/build/linux/Dockerfile-builder
        platforms: linux/amd64
#        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/r-lib/pak-builder:${{ matrix.config.r }}
        build-args: |
          R_MAJOR=${{ matrix.config.r }}
